name: Create HTML files and deploy site

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create_html:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up latest Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r scripts/script_reqs.txt
        python -m pip install -r requirements.txt
    - name: Build HTML from notebooks
      run: python -m scripts.create_notebook_html
    - name: Package HTML into docs directory    
      run: |
         mkdir -p docs
         find docs -mindepth 1 ! -name CNAME -delete
         find . -name "*.html" -not -path "./docs/*" -print0 \
           | xargs -0 -I{} cp "{}" docs/
    - name: Check for changes
      id: git_diff
      run: |
        UNTRACKED=$(git ls-files --others --exclude-standard '*.html')
        if [ -z "$UNTRACKED" ]; then
        echo "changed=false" >> $GITHUB_OUTPUT
        else
        echo "changed=true" >> $GITHUB_OUTPUT
        fi
    - name: Create PR
      if: steps.git_diff.outputs.changed == 'true'
      id: cpr
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Creating HTML files for new notebooks
        committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
        signoff: false
        delete-branch: true
        base: main
        branch: create_notebook_html_${{ github.run_id }}
        title: "Creating HTML files for new notebooks"
        token: ${{ secrets.DATACEBO_GH_TOKEN }}
    - name: Enable Pull Request Automerge
      if: steps.git_diff.outputs.changed == 'true'
      run: gh pr merge --squash --auto create_notebook_html_${{ github.run_id }}
      env:
        GH_TOKEN: ${{ secrets.DATACEBO_GH_TOKEN }}
