name: Run Notebooks

on:
  workflow_dispatch:
    inputs:
      notebook_path: 
        description: 'Filepath to the notebook relative to the datacebo-cookbook directory.'
        required: true
        type: string

jobs:
  run_notebooks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up latest Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r scripts/script_reqs.txt
        python -m pip install -r requirements.txt
    - name: Install enterprise dependencies
      run: |
        sdv-installer install --license-key ${{ secrets.LICENSE_KEY }} --username ${{ secrets.DATACEBO_USERNAME }}
    - name: Install Google Chrome for Plotly image export
      run: plotly_get_chrome -y 

    - name: 
      run: python -m scripts.run_notebook -n ${{ inputs.notebook_path }}